### ISSUE TITLE
Missing Dark Styles in Header and Message Area

### ISSUE THREAD

**Issue by alpascale** [benjamhooper/slack-custom-theme#2]
The header section that lists the name of the person you are chatting with is not styled nor is the message section at the bottom. See attached. This occurs on at least Windows 10.

![slack-dark-missing-style](https://user-images.githubusercontent.com/4072242/63864362-b4078f00-c97d-11e9-9b75-2c147b0b4d40.png)

**Comment by benjamhooper** [comment]
Thank you for your issue submission. Though my script does not directly deal with theming and layout. Its just a means of installing them. Where did you get this theme?

**Comment by alpascale** [comment]
Ah. I didn't realize that. This is the theme I used: https://raw.githubusercontent.com/earlduque/Slack-Dark-Theme/master/dark.css

**Comment by benjamhooper** [comment]
Yeah no worries! Shoot on over to https://github.com/earlduque/Slack-Dark-Theme and make an issue stating what you did above. If you need anything else feel free to open another issue! Here is the theme I use: https://github.com/caiceA/slack-black-theme this repo uses the script i've created with it built in.

**Comment by alpascale** [comment]
Thanks!
